export const dogs = [
    {
        name: "Marley",
        dob: "2015-09-06",
        size: "large",
        breed: "Labrador Retriever",
        sex: 'm',
        color: 'gold',
        desc_1: "energetic and easy to handle",
        desc_2: "takes me on walks and shows me lots of attention",
        date_entered: "2021-11-21",
        image_url: "https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=962&q=80",
        novice_friendly: 3,
        kid_friendly: 5,
        dog_friendly: 5,
        stranger_friendly: 5,
        easy_to_groom: 4,
        trainability: 5,
        energy_level: 5,
        exercise_needs: 5,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Cinderella",
        dob: "2020-01-02",
        size: "medium",
        breed: "Harrier",
        sex: 'f',
        color: 'brown',
        desc_1: "stubborn but extremely loyal and friendly",
        desc_2: "will put up with my energy and I will reward them back with hugs and kisses :)",
        date_entered: "2022-03-01",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harrier_tricolour.jpg/440px-Harrier_tricolour.jpg",
        novice_friendly: 3,
        kid_friendly: 5,
        dog_friendly: 5,
        stranger_friendly: 5,
        easy_to_groom: 5,
        trainability: 4,
        energy_level: 5,
        exercise_needs: 5,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Bella",
        dob: "2019-05-11",
        size: "large",
        breed: "Italian Greyhound",
        sex: 'f',
        color: 'grey',
        desc_1: "fast as lightning!",
        desc_2: "is always ready for a run or at least a trip to the park",
        date_entered: "2022-06-29",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Blue_greyhound.JPG/440px-Blue_greyhound.JPG",
        novice_friendly: 5,
        kid_friendly: 5,
        dog_friendly: 4,
        stranger_friendly: 4,
        easy_to_groom: 5,
        trainability: 4,
        energy_level: 4,
        exercise_needs: 4,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Doge",
        dob: "2018-12-23",
        size: "small",
        breed: "Shiba Inu",
        sex: 'm',
        color: 'white',
        desc_1: "wow, much loving, so present",
        desc_2: "is willing to take a chance on me",
        date_entered: "2021-01-19",
        image_url: "https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg",
        novice_friendly: 4,
        kid_friendly: 3,
        dog_friendly: 3,
        stranger_friendly: 3,
        easy_to_groom: 4,
        trainability: 4,
        energy_level: 4,
        exercise_needs: 3,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Balto",
        dob: "1989-10-07",
        size: "large",
        breed: "Siberian Husky",
        sex: 'm',
        color: 'black',
        desc_1: "some one who will go the distance to meet a goal or protect a friend",
        desc_2: "has the same drive and dedication as I do to dog sledding, someone who will respect me and help me achieve great things",
        date_entered: "2003-06-23",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Siberian_Husky_sable.jpg/440px-Siberian_Husky_sable.jpg",
        novice_friendly: 1,
        kid_friendly: 5,
        dog_friendly: 5,
        stranger_friendly: 5,
        easy_to_groom: 2,
        trainability: 4,
        energy_level: 5,
        exercise_needs: 5,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Maxine",
        dob: "2022-07-10",
        size: "small",
        breed: "Akita",
        sex: 'f',
        color: 'brown',
        desc_1: "independent and introverted with strangers but loyal to my family (who could be you)",
        desc_2: "respects my boundaries and trusts my abilities to protect you",
        date_entered: "2017-05-22",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Boy_c11.jpg/440px-Boy_c11.jpg",
        novice_friendly: 2,
        kid_friendly: 1,
        dog_friendly: 1,
        stranger_friendly: 2,
        easy_to_groom: 1,
        trainability: 4,
        energy_level: 4,
        exercise_needs: 4,
        created_at: "2022-07-19",
        shelter_id: 1
    },
    {
        name: "Toto",
        dob: "2020-03-14",
        size: "small",
        breed: "Cairn Terrier",
        sex: 'm',
        color: 'beige',
        desc_1: "here to help and accompany you to success",
        desc_2: "will take me on adventures and journeys",
        date_entered: "2017-05-22",
        image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Керн_терьер_%28cairn_terrier%29.jpg/440px-Керн_терьер_%28cairn_terrier%29.jpg",
        novice_friendly: 4,
        kid_friendly: 5,
        dog_friendly: 4,
        stranger_friendly: 4,
        easy_to_groom: 5,
        trainability: 4,
        energy_level: 5,
        exercise_needs: 4,
        created_at: "2022-07-19",
        shelter_id: 1
    }
]

export const milestones = [
    {
        name: "Roll",
        status: false,
        minutes: 60,
        notes: 'Today, Marley tried to roll but instead laid on his tummy and waited for a belly rub',
        dog_id: 1,
        created_at: "2022-07-01",
        updated_at: "2022-07-18"
    },
    {
        name: "Roll",
        status: false,
        minutes: 60,
        notes: 'Today, Marley tried to roll but instead laid on his tummy and waited for a belly rub',
        dog_id: 1,
        created_at: "2022-07-01",
        updated_at: "2022-07-18"
    },
    {
        name: "Sit",
        status: true,
        minutes: 180,
        notes: 'Marley did it! He sat when we told him to "sit". Incredible progress.',
        dog_id: 1,
        created_at: "2022-07-05",
        updated_at: "2022-07-10"
    },
    {
        name: "Stay",
        status: true,
        minutes: 90,
        notes: 'Marley stayed put for almost ten minutes today!',
        dog_id: 1,
        created_at: "2022-07-03",
        updated_at: "2022-07-08"
    },
    {
        name: "Roll",
        status: false,
        minutes: 60,
        notes: 'Today, Balto tried to roll but instead laid on his tummy and waited for a belly rub',
        dog_id: 2,
        created_at: "2022-07-01",
        updated_at: "2022-07-18"
    }
]

export const user_dog_pairings = [
    {
        user_id: 1,
        dog_id: 1
    },
    {
        user_id: 1,
        dog_id: 2
    }
]